### ISSUE TITLE
login window not appearing in popup (despite being set to true)

### ISSUE THREAD

**Issue by jlahijani** [amzn/login-and-pay-with-amazon-sdk-samples#13]
I integrated Amazon Pay into my site a few months ago and it was working perfectly.  Now for some reason, when a user clicks the "Amazon Pay" button, the login window no longer appears inside a popup window, but rather opens a new tab.

The code sample in this repo also suffers this same problem now too (click the gold "Amazon Pay" button):
https://amzn.github.io/login-and-pay-with-amazon-sdk-samples/simple.html

Note: the 'popup:true' setting is set on both on my site and in the sample code provided here.

**Comment by jlahijani** [comment]
Upon further inspection, it seems to be an issue with Chrome (worked fine on Firefox; didn't check other browsers).  Chrome mentions the following line **twice** in the console:

Widgets.js:67 A Parser-blocking, cross site (i.e. different eTLD+1) script, https://api-cdn.amazon.com/sdk/login1.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.

**Comment by tarishah** [comment]
@jlahijani, the Parse-blocking comment is  'warning' and will not cause the issue you have mentioned. I clicked on 'gold' Amazon Pay button in chrome and I got a popup (which is the expected behavior). Can you check on your end- if you do not have any extension or setting which will open pop-ups in a new tab?

**Comment by jlahijani** [comment]
@tarishah Based on my tests, the popup worked in Chrome v58, but when using v59, it opens a new tab instead.

**Comment by danielneu** [comment]
Hi,

this is caused by a change introduced in Chrome v59, this is being addressed internally and unrelated to the samples.

The parser blocking script notification can be omitted by loading the Widgets.js asynchronously.
Here is a minimal sample for this: https://github.com/danielneu/amazon-login-and-pay-tests/blob/master/minimal_button_sample/index.html
The samples make use of synchronous loading,

However, even with this notification present, we are making sure to fallback to asynchronous loading of the login1.js automatically inside our Widgets.js file.

Closing this issue, feel free to reopen if questions are unanswered.

Best wishes 
Daniel
